export const Currencies = [
  { value: 'USD', label: '$ Dollar', locale: 'en-US' },
  { value: 'EUR', label: '€ Euro', locale: 'eu-EU' },
  { value: 'JPY', label: '¥ Yen', locale: 'ja-JP' },
  { value: 'GBP', label: '£ Pound', locale: 'en-GB' },
  { value: 'AUD', label: '$ Australian Dollar', locale: 'en-AU' },
  { value: 'CAD', label: '$ Canadian Dollar', locale: 'en-CA' },
  { value: 'CHF', label: 'Fr Swiss Franc', locale: 'de-CH' },
  { value: 'CNY', label: '¥ Yuan', locale: 'zh-CN' },
  { value: 'SEK', label: 'kr Swedish Krona', locale: 'sv-SE' },
  { value: 'NZD', label: '$ New Zealand Dollar', locale: 'en-NZ' },
  { value: 'MXN', label: '$ Mexican Peso', locale: 'es-MX' },
  { value: 'SGD', label: '$ Singapore Dollar', locale: 'en-SG' },
  { value: 'HKD', label: '$ Hong Kong Dollar', locale: 'en-HK' },
  { value: 'NOK', label: 'kr Norwegian Krone', locale: 'no-NO' },
  { value: 'KRW', label: '₩ South Korean Won', locale: 'ko-KR' },
  { value: 'TRY', label: '₺ Turkish Lira', locale: 'tr-TR' },
  { value: 'RUB', label: '₽ Russian Ruble', locale: 'ru-RU' },
  { value: 'INR', label: '₹ Indian Rupee', locale: 'hi-IN' },
  { value: 'BRL', label: 'R$ Brazilian Real', locale: 'pt-BR' },
  { value: 'ZAR', label: 'R South African Rand', locale: 'en-ZA' },
  { value: 'PLN', label: 'zł Polish Zloty', locale: 'pl-PL' },
  { value: 'DKK', label: 'kr Danish Krone', locale: 'da-DK' },
  { value: 'THB', label: '฿ Thai Baht', locale: 'th-TH' },
  { value: 'MYR', label: 'RM Malaysian Ringgit', locale: 'ms-MY' },
  { value: 'IDR', label: 'Rp Indonesian Rupiah', locale: 'id-ID' },
  { value: 'CZK', label: 'Kč Czech Koruna', locale: 'cs-CZ' },
  { value: 'HUF', label: 'Ft Hungarian Forint', locale: 'hu-HU' },
  { value: 'ILS', label: '₪ Israeli Shekel', locale: 'he-IL' },
  { value: 'CLP', label: '$ Chilean Peso', locale: 'es-CL' },
  { value: 'PHP', label: '₱ Philippine Peso', locale: 'fil-PH' },
  { value: 'AED', label: 'د.إ UAE Dirham', locale: 'ar-AE' },
  { value: 'SAR', label: '﷼ Saudi Riyal', locale: 'ar-SA' },
  { value: 'TWD', label: 'NT$ New Taiwan Dollar', locale: 'zh-TW' },
  { value: 'VND', label: '₫ Vietnamese Dong', locale: 'vi-VN' },
  { value: 'PKR', label: '₨ Pakistani Rupee', locale: 'ur-PK' },
  { value: 'EGP', label: '£ Egyptian Pound', locale: 'ar-EG' },
  { value: 'KWD', label: 'د.ك Kuwaiti Dinar', locale: 'ar-KW' },
  { value: 'BDT', label: '৳ Bangladeshi Taka', locale: 'bn-BD' },
  { value: 'UAH', label: '₴ Ukrainian Hryvnia', locale: 'uk-UA' },
  { value: 'QAR', label: '﷼ Qatari Riyal', locale: 'ar-QA' },
  { value: 'NGN', label: '₦ Nigerian Naira', locale: 'en-NG' },
];

export type Currency = (typeof Currencies)[0];
